### ISSUE TITLE
problem with storing the values

### ISSUE THREAD

**Issue by Boby900** [Boby900/weather-app#1]
#2 
-  After providing the input values I am able to console out the latitude and longitude but later I want to use that values so I can add one more _API(weather apis which need **lat & lon** of city)_ which will display the current weather

- so can please help me on to how to store that logged out values in the variables so later I can use that.

**Comment by shabarishkera** [comment]
declare a variable outside the arrow function and asign its values inside the function

**Comment by Boby900** [comment]
thanks @shabarishkera , your advice resolved my problem.
