### ISSUE TITLE
problem with rerouting

### ISSUE THREAD

**Issue by Boby900** [Boby900/weather-app#2]
#1 
this app was up and running and logging out the values, but as I had deployed it on GitHub pages it's not working  and while I am clicking on the this [link](https://boby900.github.io/weather-app/) provided by GitHub pages it's throwing off the bugs, and font size also seems to be smaller.

![Screenshot (31)](https://user-images.githubusercontent.com/111265239/217222507-2ab1a5de-f7db-47c1-8df1-248ca6953f6e.png)

**Comment by Abhishek7Tech** [comment]
Hi @Boby900 it's due to weatherapi url it starts with http which isn't secure try using https.

**Comment by Boby900** [comment]
thanks @Abhishek7Tech , now it's working.
