### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by Boby900** [Boby900/weather-app#5]
I am trying to display the result with one button only but I have to use two buttons separately for the different functions, If you can help me do display the result with the one button only instead of two.
Your efforts will be highly admirable.
![Screenshot (34)](https://user-images.githubusercontent.com/111265239/217821811-595f4bea-e701-4947-9d61-313bbef46633.png)
.

**Comment by tenyapious** [comment]
Hi Boby900, I would be happy to help you with that, I'm submitting a PR

**Comment by Boby900** [comment]
#8
